#
#services:
#  postgres:
#    image: postgres:latest
#    container_name: crm-postgres
#    restart: always
#    volumes:
#      - crm_data:/var/lib/postgresql/data
#    environment:
#      POSTGRES_DB: 'crm'
#      POSTGRES_USER: 'verteksar'
#      POSTGRES_PASSWORD: '1234qwer'
#    ports:
#      - "5433:5432"
#  crm:
#    build:
#      dockerfile: ./Dockerfile
#    restart: always
#    command: sh -c "
#      python manage.py migrate &&
#      python manage.py collectstatic --noinput &&
#      python manage.py createsuperuser --noinput &&
#      gunicorn crm.wsgi:application --bind 0.0.0.0:8711 --log-level debug"
#    expose:
#      - 8711
#    environment:
#      - DEBUG=0
#    depends_on:
#      - postgres
#
#volumes:
#  crm_data:

services:
  postgres:
    image: postgres
    container_name: crm-postgres1
    environment:
#      POSTGRES_PASSWORD: 1234qwer
      POSTGRES_DB: crm
      POSTGRES_USER: verteksar
      POSTGRES_PASSWORD: 1234qwer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  crm:
    build: .
    container_name: crm1
    restart: always
    command: bash -c "python manage.py migrate && gunicorn crm.wsgi:application --bind 0.0.0.0:8000 --log-level debug"
    ports:
      - 8711:8000
    depends_on:
      - postgres
volumes:
  postgres_data:
