# Generated by Django 5.0.3 on 2024-04-13 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('users', '0005_alter_management_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.lead'),
        ),
    ]
