# Generated by Django 4.2.5 on 2024-09-02 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_alter_contract_end_date'),
        ('users', '0007_alter_lead_phone'),
        ('customers', '0003_alter_customer_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contract', verbose_name='Контракт'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.lead', verbose_name='Пользователь'),
        ),
    ]
