# Generated by Django 5.0.3 on 2024-04-03 10:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата заключения'),
        ),
    ]
