# Generated by Django 5.0.3 on 2024-04-03 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_alter_contract_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 4, 12, 23, 53, 794925, tzinfo=datetime.timezone.utc), verbose_name='Дата расторжения'),
        ),
    ]
