# Generated by Django 4.2.5 on 2024-09-02 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_alter_contract_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 3, 16, 23, 52, 948668, tzinfo=datetime.timezone.utc), verbose_name='Дата расторжения'),
        ),
    ]
